export { default as api, registerAdapter, isTauri } from './api/index.js';
export { useFilesStore }            from './stores/useFilesStore.js';
export { useDesignStore }           from './stores/useDesignStore.js';
export { default as FileManager }          from './components/FileManager.vue';
export { default as DesignWizard }         from './components/DesignWizard.vue';
export { default as SchematicDiagram }     from './components/SchematicDiagram.vue';
export { default as BoardLayout }          from './components/BoardLayout.vue';
export { default as BOMPanel }             from './components/BOMPanel.vue';
export { default as TransformerConstruction } from './components/TransformerConstruction.vue';
export { default as DesignNotes }          from './components/DesignNotes.vue';
export { default as DesignTreePanel }      from './components/DesignTreePanel.vue';
export { COMPONENT_DB, DESIGN_TREE }       from './data/ComponentDatabase.js';
export { buildUds, applyDbComponent, compLabel } from './data/udsSchema.js';
export { default as ComponentsManager } from './components/ComponentsManager.vue';
export { default as MagneticsDatabase } from './components/MagneticsDatabase.vue';
export { default as MagneticsDesigner } from './components/MagneticsDesigner.vue';
export { default as WelcomeScreen }       from './components/WelcomeScreen.vue';
export { default as ProductPortfolio }    from './components/ProductPortfolio.vue';
export { default as ComponentSetsManager}  from './components/ComponentSetsManager.vue';
export { default as HelpSystem }          from './components/HelpSystem.vue';
export { default as AppMenuBar }    from './components/AppMenuBar.vue';
export { useI18n, LANGUAGES }       from './composables/useI18n.js';
export { runSimulation, generateVariants } from './engine/SimEngine.js';
